### ISSUE TITLE
andriod代码没有提交全吧

### ISSUE THREAD

**Issue by yzj578492228** [yisar/smallapp#33]
andriod代码没有提交全吧 光写了支持

**Comment by schizobulia** [comment]
是遗漏了，已经在提pr，可以参考：https://github.com/yisar/smallapp/pull/34

**Comment by schizobulia** [comment]
需要运行在Android环境时，启动流程有个小变化。在执行debug.sh之前需要先不启动web的serve，要不然后续无法拷贝Android需要的文件。

**Comment by yzj578492228** [comment]
> 需要运行在Android环境时，启动流程有个小变化。在执行debug.sh之前需要先不启动web的serve，要不然后续无法拷贝Android需要的文件。

👌
